USE banco1;

CREATE TABLE `tabela1` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `coluna_varchar_1` VARCHAR(291),
    `coluna_varchar_2` VARCHAR(291),
    `coluna_varchar_3` VARCHAR(291),
    `coluna_varchar_4` VARCHAR(291),
    `coluna_varchar_5` VARCHAR(291),
    `coluna_varchar_6` VARCHAR(291),
    `coluna_varchar_7` VARCHAR(291),
    `coluna_varchar_8` VARCHAR(291),
    `coluna_varchar_9` VARCHAR(291),
    `coluna_varchar_10` VARCHAR(291),
    `coluna_varchar_11` VARCHAR(291),
    `coluna_varchar_12` VARCHAR(291),
    `coluna_varchar_13` VARCHAR(291),
    `coluna_varchar_14` VARCHAR(291),
    `coluna_varchar_15` VARCHAR(291),
    `coluna_text_1` TEXT,
    `coluna_text_2` TEXT,
    `coluna_text_3` TEXT,
    `coluna_text_4` TEXT,
    `coluna_text_5` TEXT,
    `coluna_int_1` INT,
    `coluna_int_2` INT,
    `coluna_int_3` INT,
    `coluna_int_4` INT,
    `coluna_int_5` INT,
    `coluna_int_6` INT,
    `coluna_int_7` INT,
    `coluna_int_8` INT,
    `coluna_int_9` INT,
    `coluna_int_10` INT,
    `coluna_int_11` INT,
    `coluna_int_12` INT,
    `coluna_int_13` INT,
    `coluna_int_14` INT,
    `coluna_int_15` INT,
    `coluna_int_16` INT,
    `coluna_int_17` INT,
    `coluna_int_18` INT,
    `coluna_int_19` INT,
    `coluna_int_20` INT,
    `coluna_double_1` DOUBLE,
    `coluna_double_2` DOUBLE,
    `coluna_double_3` DOUBLE,
    `coluna_double_4` DOUBLE,
    `coluna_double_5` DOUBLE,
    `coluna_double_6` DOUBLE,
    `coluna_double_7` DOUBLE,
    `coluna_double_8` DOUBLE,
    `coluna_double_9` DOUBLE,
    `coluna_double_10` DOUBLE,
    `coluna_double_11` DOUBLE,
    `coluna_double_12` DOUBLE,
    `coluna_double_13` DOUBLE,
    `coluna_double_14` DOUBLE,
    `coluna_double_15` DOUBLE,
    `coluna_double_16` DOUBLE,
    `coluna_double_17` DOUBLE,
    `coluna_double_18` DOUBLE,
    `coluna_double_19` DOUBLE,
    `coluna_double_20` DOUBLE,
    PRIMARY KEY (`id`),
    INDEX `idx_coluna_int_1` (`coluna_int_1`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;